services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browser
    image: browser:latest
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html/src  # Mountet den src/ Ordner
      - ./public:/var/www/html/public  # Mountet den public/ Ordner für Apache
      - ./apache-custom.conf:/etc/apache2/sites-available/000-default.conf  # Apache-Konfigurationsdatei einbinden
    restart: always
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "meinprojekt"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8009:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data:

